apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: my-nodejs-app
        image: <your-docker-image> # replace with your Docker image
        ports:
        - containerPort: 3002
        env:
        - name: MY_ENV_VAR
          value: "my-value"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3002
  selector:
    app: my-nodejs-app